### ISSUE TITLE
Feedback on Andrea's file (not pertaining to issue 14)

### ISSUE THREAD

**Issue by sgrellet** [INSIDE-information-systems/WFS3#15]
other questions on Andrea's file mentionned in #14
* id : 
	* don't reuse GML id but instead the trailing part of the URI
https://data.geoscience.fr/id/well/BSS000AAAA -> "id": "BSS000AAAA"
	* see Kathi's issue : https://github.com/INSIDE-information-systems/WFS3/issues/12

* flipped coordinates for Borehole and bholeHeadworks
They need to be flipped because GeoJSON expects CRS 84. Otherwise our groundwater Wells end-up in the ocean near Somalia. See conclusions from https://github.com/INSIDE-information-systems/WFS3/issues/2

* "name": "when available" does not appear in the example output : you confirm it will be like this when finding content in the database ?

* "sampledFeature": [
	*it seems it does not behave like the other href/title patterns as we don't  have : "@href": "https://sweet.jpl.nasa.gov/2.3/realmEarthReference.owl#EarthLithosphere", "@title": "Lithosphere"]} and it adds extra {} for each xml attibute
	* it shouldn't contain href/title to SANGATTE (name and city) -> which should be under locatedOnAdminUnit property

* no custodianPeriod ?

* legalAccessLevel
@dataType or featureType ? -> was that a mistake in our sample file ? -> cross checking with gmd.xsd it's a plain class (not stereotyped). 
+1 for @dataType not to introduce extra semantics in our GeoJSON

* CI_RoleCode
"dataType": "CI_RoleCode" replaced by "@dataType": "CodeListValue" -> we feel it should be "@dataType": "CI_RoleCode"

* "links": [
	* "rel": "self", "href": "http://localhost:8080/geoserver/wfs3/collections/eposb__Borehole/items?f=application%2Fgeo%2Bjson"
	does not seem to be the right URL for the collection as there is no guarantee this will deliver feature which id is BSS000AAAA (unless that the only one in the collection)
	* comes from WFS3, just need to keep in mind the writing convention differs from @title, @href, ....

**Comment by aaime** [comment]
A few answers:

- About the id, nothing we can do, the GeoJSON is not a remapping format, it just represents the data as it comes from the datastore. If you want a URL, it would have to be either generated that way in the app-schema, as the feature id, or you can wait for the json-ld backmapping code, which will allow to do pretty much whatever one wants (with some code variations it could be used to generate a custom GeoJSON output too).
- The CRS is odd, the code in WFS3 tries to force CRS84, it's either a general reprojection issue with complex features or there is a setup problem (e.g., if the data does not have a CRS in the database for example). Might be a setup problem, when trying to get the GML2 I get an exception, "java.lang.RuntimeException: Failed to get properties. The coordinate reference system must be the same for all objects." Have to check.
- About the sampled feature, the example from the previous ticket showed a work in progress meant to discuss the @datatype. Here is an up to date version: https://gist.githubusercontent.com/aaime/d2c1cf46895aad2706ea871bbfa1c96f/raw/238dd828066cf9022493b3e4ca52a9f8a57b5c4d/borehole2.json
 (not sure about SANGATTE, it seems to be coming from the data)
- The custodianPeriod is missing from the mappings
- CI_RoleCode is a element name, not a type, in the schema, what I can pull off is either always the element name or the type name, but not a mix of them on a case by case basis (this is again something that the freeform mapping output format will be able to do instead) . See the following XML schema diagram:

![image](https://user-images.githubusercontent.com/325433/56055176-2a05b380-5d59-11e9-8efb-22c5a8b3f30e.png)

- The links show up in the GeoJSON as they are generated from app-schema.

**Comment by KathiSchleidt** [comment]
some feedback, both to this and some bits probably from #14 

**@dataType**
@dataType is often there, sometimes missing. Think there's a SW bug as mentioned in my mail. Usually, length is provided without @dataType, but there's an exception to this rule -  "@dataType": "Measure" is provided in the case that there is no value (close, but not quite there yet! ;) )

**sampledFeature**
Strange is that locatedOnAdminUnit is also provided under sampledFeature (in the app schema mapping its still locatedOnAdminUnit). The lack of a URI in the @href of locatedOnAdminUnit is because the base URL was missing, thus currently only contains strconcat( num_departement, code_insee)
"@title": "SANGATTE" comes from nom_commune
To my view, both sampledFeature and locatedOnAdminUnit should be "@dataType": "Reference", but provided under their proper names (sampledFeature and locatedOnAdminUnit respectively)
		
**eposb:custodianPeriod**
eposb:custodianPeriod was empty in original mapping file, and thus got lost in further translation. Give me a db mapping and I'm glad to map!

**Comment by sgrellet** [comment]
Some additionnal feedback (I'll contribute separately on ids in the dedicated issue)

**@dataType** same comment

**locatedOnAdminUnit** : indeed should be in its proper XML tag
regarding the @href, the mapping file should be updated to <value>strconcat('http://id.insee.fr/geo/commune/', code_insee)</value>
no need to fetch 'num_departement' from the DB it's already in code_insee 
should be in the latest mapping file I hope 

**eposb:custodianPeriod**
@spifman will provide you with the info

**Comment by aaime** [comment]
On Sun, May 5, 2019 at 4:07 PM KathiSchleidt <notifications@github.com>
wrote:

> some feedback, both to this and some bits probably from #14
> <https://github.com/INSIDE-information-systems/WFS3/issues/14>
>
> *@datatype <https://github.com/datatype>*
> @datatype <https://github.com/datatype> is often there, sometimes
> missing. Think there's a SW bug as mentioned in my mail. Usually, length is
> provided without @datatype <https://github.com/datatype>, but there's an
> exception to this rule - "@datatype <https://github.com/datatype>":
> "Measure" is provided in the case that there is no value (close, but not
> quite there yet! ;) )
>

Indeed the heuristic to determine if an element is a "complex type with
simple content" is failing there, because the value is missing.
As a reminder, the expected situation is that the object does not have
a @dataType for any complex type with simple content.

I've made some changes to the code, so that it uses the datatype and does
not encode the @dataType for anything extending XML's anySimpleType,
here is a before/after diff:

http://www.mergely.com/w0nJwHqa/

Notes:

   - The boreCollarPositionalAccuracy is still there because the app-schema
   mappings require it to be there (it's also there in the GML output), me and
   Nuno have looked at possibilities to make it go completely but it would
   require some changes to the app-schema that are not trivial. A possible
   compromise would be to encode the UOM as a an empty string, and make the
   JSON encode skip the boreCollarPositionalAccuracy property entirely in that
   case (rule, skip a simple type if there are no attribute or if the
   attributes are all empty strings)
   - All the codelist lose the @dataType because they are another case of
   complex element with simple content, which the code was not catching
   correctly before, due to the fact a codeList is meant to have only
   attributes and never an actual string content.

About the latter, it's interesting to note how the schema does not make it
possible to figure out if a complex with simple content is meant to have a
content at all. See below, Measure is meant to have a context, CodeList
not, but structually they are the same:

<complexType name="MeasureType">
    <simpleContent>
        <extension base="double">
            <attribute name="uom" type="gml:UomIdentifier" use="required"/>
        </extension>
    </simpleContent>
</complexType>

vs

<complexType name="CodeListValue_Type">
    <simpleContent>
        <extension base="xs:string">
            <attribute name="codeList" type="xs:anyURI" use="required"/>
            <attribute name="codeListValue" type="xs:anyURI"
use="required"/>
            <attribute name="codeSpace" type="xs:anyURI"/>
        </extension>
    </simpleContent>
</complexType>

in the codelist the "xs:string" base is just an excuse to attach
attributes... not sure why an actual complex with just a list of attributes
was not used instead, but it's there in an OGC schema, not much we can do
about it I believe....

Cheers
Andrea



-- 

Regards, Andrea Aime == GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information. == Ing. Andrea Aime
@geowolf Technical Lead GeoSolutions S.A.S. Via di Montramito 3/A 55054
Massarosa (LU) phone: +39 0584 962313 fax: +39 0584 1660272 mob: +39 339
8844549 http://www.geo-solutions.it http://twitter.com/geosolutions_it
------------------------------------------------------- *Con riferimento
alla normativa sul trattamento dei dati personali (Reg. UE 2016/679 -
Regolamento generale sulla protezione dei dati “GDPR”), si precisa che ogni
circostanza inerente alla presente email (il suo contenuto, gli eventuali
allegati, etc.) è un dato la cui conoscenza è riservata al/i solo/i
destinatario/i indicati dallo scrivente. Se il messaggio Le è giunto per
errore, è tenuta/o a cancellarlo, ogni altra operazione è illecita. Le
sarei comunque grato se potesse darmene notizia. This email is intended
only for the person or entity to which it is addressed and may contain
information that is privileged, confidential or otherwise protected from
disclosure. We remind that - as provided by European Regulation 2016/679
“GDPR” - copying, dissemination or use of this e-mail or the information
herein by anyone other than the intended recipient is prohibited. If you
have received this email by mistake, please notify us immediately by
telephone or e-mail.*

**Comment by sgrellet** [comment]
Thanks Andrea.

- Regarding 'boreCollarPositionalAccuracy'
Could we solve this with a combination of 
```xml
<encodeIfEmpty>false</encodeIfEmpty>
```
 (maybe this is unnecessary because that's the default behaviour)
AND "http://qudt.org/vocab/unit/CM" being stored in the DB (and only written in the DB in case we do have a Measure) and not hard coded in the mapping file ?

- regarding @datatype new adjustments looks like they should be added to the summary doc

**Comment by KathiSchleidt** [comment]
the attributes without a value have been shifted to https://github.com/INSIDE-information-systems/WFS3/issues/22

**Comment by KathiSchleidt** [comment]
Should we leave this thread open, or close and just follow the individual issues I pulled out. I'll close for now, see if somebody wishes to reopen
