### ISSUE TITLE
Helsinki INSPIRE 2019 - Data Challenge (Work In Progress)

### ISSUE THREAD

**Issue by nmco** [INSIDE-information-systems/WFS3#23]
## Summary (~100 words)
> - sell your challenge to the teams, why is this interesting?

The publication of INSPIRE data sets usually involves the mapping of the source of the data, for example a data base, to the target GML schema(s). Then some software, [for example GeoServer App-Schema](https://docs.geoserver.org/stable/en/user/data/app-schema/index.html#application-schemas), will be responsible to understand those mappings and produce the final GML document as well to support querying on those GML documents, usually through [OGC WFS service](https://www.opengeospatial.org/standards/wfs).

After INSPIRE data sets have been published and used in real applications, some common requirements have started to emerge:
- GML is very powerful, but more wildly supported and friendly formats, like JSON, would be preferred, specially when building Web applications. 
 - Querying the data should be fast, the software in the middle needs to be able to bring the query computation to the original data source. 

Recent [OGC  WFS 3.0](https://github.com/opengeospatial/WFS_FES) work is following an interesting approach: JSON has the core format, REST like API and basically build on top of modern Web technologies. Existing implementations, [like GeoServer](https://www.geo-solutions.it/blog/wfs3-geoserver/), are accommodating their stack to be able to server INSPIRE data sets through WFS 3.0 using JSON and JSON-LD output formats. BRGM has been caring on some experiments with this approach using _Bore Holes_ data set. 

## Key issues to questions to answer/investigate
This shift to modern Web technologies and JSON like formats bring several challenges and raise several questions:
- Should existing solutions keep using GML as  first class citizen and in some way be blend to support JSON outputs on top of the GML?
- In the past years, a lot of efforts have been put in the definition of GML schemas, shoudl this work be completely throw away and pure JSON or JSON-LD models be created? 
- Is the current tendency, which is an automatic translation from GML to JSON like structures realistic?
- What could be the optimal mappings support format that would allow the definition of the mappings between several data sources (PostgreSQL, Solr, MongoDB, ...) and atgret output format (GML, JSON, JSON-LD, etc ...).
- How will the answers to the questions above impact the querying capabilities of WFS 3.0? 

## Required knowledge and skills
- Data modelling and data management skills
- INSPIRE data sets mappings publishing skills 
- Knowledge of OGC standards, the focus will be on WFS 3.0
- Knowledge of JSON based formats: GeoJSON and JSONLD 

## Offered datasets
> - Spatial (or other) datasets your organisation(s) already have available that may be relevant for 
> solving the issues (e.g. file based, via APIs, database dumps)?
> - Geographical and temporal extent of the provided datasets
> - Access details and licencing conditions
> - Would you like to get support for publishing your data to challenge teams via temporary APIs 
> (WFS2/WFS3, etc.)?

Boreholes?

## Other relevant datasets
> - Datasets provided by someone else that you know may be relevant for your challenge
> - Access details

## New technologies to test or evaluate
- GeoServer JSON and JSON-LD support
- OGC WFS 3.0 work

## Offered personal resources
> - How much expert working time per week can you offer to the teams working with your challenge,
> datasets and APIs during the work on the challenge?
> - Desired form of communicating with the teams?

Not decide yet.

## Offered or suggested tools
- tools for data processing, storing or visualisation (free, or ones you can provide licenses for the duration of the challenge)
- tools for team collaboration / coding, etc. (free, or ones you can provide licenses for the duration of the challenge)

## Desired outcome and presentation
- How would you like the teams to deliver and present the results of their work: online demo, proof-of-concept software, website, mobile app, presentation, etc.

## Offered benefits for the teams
- Besides learning what can you offer to the teams that participate in your challenge?
- Can you provide access to interesting data that's normally not publicly available?
- Are you able to award the winning team with money, vouchers, gifts, etc.?

## Background & context
- How does your challenge relate to the [Inspire Helsinki 2019](https://www.inspire-helsinki-2019.fi) themes of sea/oceans, weather/outdoor conditions, or cities/urban living?
- How does your challenge relate to INSPIRE (It does not have to!), European spatial datasets, or spatial data infrastructures?
- Examples of use cases, applications, or previous hackathons/challenges where your datasets and/or APIs have already been used for before

## Cooperation with other Challenge Partners 
In order to create 3 to 4 high-quality final challenges, the organisers may suggest that some of the partners submit a combined final challenge.
- Are you interested in hosting your challenge together with one or more of the other challenge partners or submitting a common proposal?
- If requested, are you able to provide access to your offered datasets, APIs or tools for a challenge proposed by another submitter?

## Submitting organisations
- Name(s) and contact details of the submitting organisation(s)
- Name and contact details of the challenge proposing group contact point (email required)

**Comment by sgrellet** [comment]
## Summary (~100 words)
> - sell your challenge to the teams, why is this interesting?

The publication of INSPIRE data sets in the environmental domain usually involves the exposition of real world features, observation generated by monitoring activities and the associated codeLists.

This activity involves mapping the source of the data, for example a database, to the target schema(s). 
The INSPIRE recommended pattern involves  [OGC WFS service](https://www.opengeospatial.org/standards/wfs) in its version 2 and SOS.

Then some software, [for example GeoServer App-Schema](https://docs.geoserver.org/stable/en/user/data/app-schema/index.html#application-schemas), are responsible to understand those mappings and produce the final GML document as well to support querying on those GML documents.

After INSPIRE data sets have been published and used in real applications, some common requirements have started to emerge:
- GML is very powerful, but more wildly supported and web developper friendly formats, like JSON (and it's derivated), would be preferred, specially when building Web applications. 
- Querying the data should be fast, the software in the middle needs to be able to bring the query computation to the original data source. 

Recent OGC APIs work is following an interesting approach: JSON has the core format, REST like API and basically build on top of modern Web technologies.
Core example are [WFS 3.0](https://github.com/opengeospatial/WFS_FES) and [Sensorthings API](https://www.opengeospatial.org/standards/sensorthings).

BRGM has been caring on some experiments, deploying these APIs on top of its Ground Water Information System (GIN) Linking those data as much as possible. Also taking into account recent OGC work on this aspect in its Environmental Linked Features Interoperability Experiment - and follow-up IE ([ELFIE](https://www.opengeospatial.org/projects/initiatives/elfie) & [SELFIE](https://www.opengeospatial.org/projects/initiatives/selfie)).

BRGM GIN has been presented in OGC and INSPIRE gathering many times; [for example in the OGC HydroDWG](https://external.opengeospatial.org/twiki_public/pub/HydrologyDWG/WorkshopTuscaloosa2017/20170620_QGIS_GDAL_OGR_complex_feature_Grellet_groundwater_monitoring.pptx%20).

Choosen implementations are 
- [GeoServer](https://www.geo-solutions.it/blog/wfs3-geoserver/): which is accommodating his stack to be able to server INSPIRE data sets through WFS 3.0 using JSON and JSON-LD output formats.
- [FROST](https://github.com/FraunhoferIOSB/FROST-Server): for the Sensorthings API implementation

## Key issues to questions to answer/investigate
This shift to modern Web technologies and JSON like formats bring several challenges and raise several questions:
- Should existing solutions keep using GML as  first class citizen and in some way be blend to support JSON outputs on top of the GML?
- In the past years, a lot of efforts have been put in the definition of GML schemas, shoudl this work be completely throw away and pure JSON or JSON-LD models be created? 
- Is the current tendency, which is an automatic translation from GML to JSON like structures realistic?
- What could be the optimal mappings support format that would allow the definition of the mappings between several data sources (PostgreSQL, Solr, MongoDB, ...) and atgret output format (GML, JSON, JSON-LD, etc ...).
- How will the answers to the questions above impact the querying capabilities of WFS 3.0? 

## Required knowledge and skills
- Data modelling and data management skills
- INSPIRE data sets mappings publishing skills 
- Knowledge of OGC standards especially on WFS 3.0 and SensorThings API Part 1
- Knowledge of JSON based formats: GeoJSON and JSON-LD 

## Offered datasets
- Borehole/Wells, ground water monitoring facility (Piezometer), Timeseries observation, Hydrogeological unit
- Associated codeLists exposed according to INSPIRE register federation practices
- Geographical coverage : France
- Temporal coverage : some Timeseries go way back in time

## Other relevant datasets
> - Datasets provided by someone else that you know may be relevant for your challenge
> - Access details

## New technologies to test or evaluate
- GeoServer JSON and JSON-LD support
- OGC WFS 3.0 work
- OGC SensorThings API Part 1

## Offered personal resources
- INSPIRE expertise
- OGC expertise
- Linkeddata expertise
- In-depth knowledge of the service stack deployed
- In-depth knowledge of the datasets exposed

> - How much expert working time per week can you offer to the teams working with your challenge,
> datasets and APIs during the work on the challenge?
> - Desired form of communicating with the teams?

Not decide yet.

## Offered or suggested tools
- tools for data processing, storing or visualisation (free, or ones you can provide licenses for the duration of the challenge)

QGIS GMLAS toolbox pluging could be an interesting GIS desktop way to access this.

- tools for team collaboration / coding, etc. (free, or ones you can provide licenses for the duration of the challenge)

## Desired outcome and presentation
- How would you like the teams to deliver and present the results of their work: online demo, proof-of-concept software, website, mobile app, presentation, etc.

Consuming this web of ground water data and generate news apps, knowledge, ideas from it.

## Offered benefits for the teams
- Besides learning what can you offer to the teams that participate in your challenge?
A change of paradigme in data discovery, access and reuse

- Can you provide access to interesting data that's normally not publicly available?

They are publicly available but not in that 'easiest' and linked flavour
- Are you able to award the winning team with money, vouchers, gifts, etc.?

Not evaluated yet

## Background & context
- How does your challenge relate to the [Inspire Helsinki2019](https://www.inspire-helsinki-2019.fi) themes of sea/oceans, weather/outdoor conditions, or cities/urban living?

Monitoring of the groundwater resource is key in a climate change context
- How does your challenge relate to INSPIRE (It does not have to!), European spatial datasets, or spatial data infrastructures?

New paradigm to expose linked environmental datasets using modern OGC APIs while keeping INSPIRE compliancy as much as possible.
- Examples of use cases, applications, or previous hackathons/challenges where your datasets and/or APIs have already been used for before

BRGM GIN has been used in FOSS4G-EU events : on SOS (52N workshops), QGIS GMLAS workshop and OsGeoLive 

## Cooperation with other Challenge Partners 
In order to create 3 to 4 high-quality final challenges, the organisers may suggest that some of the partners submit a combined final challenge.
- Are you interested in hosting your challenge together with one or more of the other challenge partners or submitting a common proposal?

Yes
- If requested, are you able to provide access to your offered datasets, APIs or tools for a challenge proposed by another submitter?

Yes, after impact/workload evaluation

## Submitting organisations
- DataCove : Kathi Schleidt <kathi@datacove.eu>
- Geosolutions it : Nuno Oliveira <nuno.oliveira@geo-solutions.it>; Simone Giannecchini <simone.giannecchini@geo-solutions.it>
- Fraunhofer IOSB : Hylke van der Schaaf <hylke.vanderschaaf@iosb.fraunhofer.de>
- BRGM : s.grellet@brgm.fr
